#!/bin/sh

# Set these paths appropriately

BIN=/home/lillo/org/courses/ailct/project/src/baseline/bin
CMD=/home/lillo/org/courses/ailct/project/src/baseline/cmd
LIB=/home/lillo/org/courses/ailct/project/src/baseline/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
