#!/bin/sh

# Set these paths appropriately

BIN=/home/lillo/org/courses/ailct/project/src/baseline/bin
CMD=/home/lillo/org/courses/ailct/project/src/baseline/cmd
LIB=/home/lillo/org/courses/ailct/project/src/baseline/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan-utf8.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
