#!/bin/sh

# Set these paths appropriately

BIN=/home/lillo/org/courses/ailct/project/src/baseline/bin
CMD=/home/lillo/org/courses/ailct/project/src/baseline/cmd
LIB=/home/lillo/org/courses/ailct/project/src/baseline/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
